base: &base
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  socket: <%= ENV['DB_SOCKET'] %>
  adapter: mysql

development: &development
  <<: *base
  database: curatious_development

test: &test
  <<: *base
  database: curatious_test

production: &production
  <<: *base
  database: curatious_production
